# Base configs
baseurl: "https://deinon-daemon.github.io/photography"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Benjamin Carsley"
subtitle: "film photo, some digital, as well as my archival / small press projects"
author: "Benjamin Carsley"
header:
 title: "Camera Caesura"
 subtitle: "by Benjamin Carsley"
footer:
 name: "Benjamin Carsley"
 bio: "Film Photographer of many formats [35mm, Med-Format, Large Format, Instant], Aspiring Darkroom Photo Chemistry Alchemist, Camera Repair Enthusiast, Archivist, Small Press Publisher, Scribbler of Fragments, Translations, and more."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork this repo on github</a> ;)"
web_design: "BC"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/sans.honte.press"
  github: "https://www.github.com/deinon-daemon"
